baseURL = 'https://aliceyt24.github.io'
languageCode = 'en-us'
title = 'Alice Y Taylor'
theme = 'hugo-resume'

PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Denver, CO USA   ·   Rio de Janeiro, Brazil"
email = "alice.taylor@du.edu"
favicon = "/favicon.ico"
colorCSS = "css/color.css"
firstName = "Alice Y"
lastName = "Taylor"
profileImage = "img/alice-headshot.png"
showEducation = true
showTeaching = true
showProjects = true
showPublications = true
showConferences = false

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://twitter.com/aliceyt24"
name = "Twitter"

[[params.handles]]
link = "https://www.linkedin.com/in/aliceytaylor/"
name = "LinkedIn"

[[params.handles]]
link = "https://www.instagram.com/aliceytaylor/"
name = "Instagram"
[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
